// this file was generated by pack packer v0.8.0

#pragma once

#define testpack_pack "testpack.pack"
#define testpack_pack_file_count 1
static const char *testpack_pack_files[] = {
    "test_file.txt",
};

#define testpack_pack__test_file_txt 0
