// this file was generated by better-cmake
// packer v0.8.2

#define packer_NAME "packer"
#define packer_AUTHOR "DaemonTsun"
#define packer_VERSION "0.8.2"
#define packer_VERSION_MAJOR 0
#define packer_VERSION_MINOR 8
#define packer_VERSION_PATCH 2
