// this file was generated by better-cmake
// pack v0.8.2

#define pack_NAME "pack"
#define pack_AUTHOR "DaemonTsun"
#define pack_VERSION "0.8.2"
#define pack_VERSION_MAJOR 0
#define pack_VERSION_MINOR 8
#define pack_VERSION_PATCH 2
