
# pack cmake package
# defines functions for integrating pack into cmake projects

macro(add_package NAME OUT_PATH)
    set(_OPTIONS)
    # TODO: add single val arg for inc
    set(_SINGLE_VAL_ARGS BASE)
    set(_MULTI_VAL_ARGS FILES)

    cmake_parse_arguments(ADD_PACKAGE "${_OPTIONS}" "${_SINGLE_VAL_ARGS}" "${_MULTI_VAL_ARGS}" ${ARGN})

    if (NOT DEFINED ADD_PACKAGE_FILES)
        message(FATAL_ERROR "add_package: missing FILES")
    endif()

    message(" pack: package ${NAME}")
    message("       base path ${ADD_PACKAGE_BASE}")
    message("  files:")

    set(_INDEX "# this file was generated by CMake pack\n\n")

    foreach(_FILE ${ADD_PACKAGE_FILES})
        message("  ${_FILE}")
        set(_INDEX "${_INDEX}${_FILE}\n")
    endforeach()

    file(WRITE "${OUT_PATH}_index" "${_INDEX}")

    # TODO: execute packer
endmacro()
